name: "agripredict"

services:
  api:
    container_name: "agripredict-api"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8000" # Just Coz I am crazy af
    volumes:
      - .:/app
      - ./logs:/app/logs/

networks:
  agripredict-network:
    name: agripredict-network
    driver: bridge
