name: "agripredict"

services:
  api:
    container_name: "agripredict-api"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8000" # Just Coz I am crazy af
    volumes:
      - .:/app
      - ./logs:/app/logs/
    healthcheck:
      test: >
        /bin/sh -c "curl -s http://127.0.0.1:8000/health | grep -q '{\"status\":\"ok\"}'"
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  agripredict-network:
    name: agripredict-network
    driver: bridge
