name: "Agripredict Docker Test"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
   docker-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Build, Start and Test Docker Compose
        run: |
          docker compose up -d --build
          
          echo "Waiting for the API to start on localhost:8080..."
          MAX_RETRIES=30
          RETRY_INTERVAL=5

          for i in $(seq 1 $MAX_RETRIES); do
            if curl -v http://127.0.0.1:8080/health 2>&1 | grep -q 'HTTP/2 200' && curl -s http://127.0.0.1:8080/health | grep -q '{"status":"ok"'; then
              echo "API is ready after $((i * RETRY_INTERVAL)) seconds!"
              exit 0
            fi
            echo "API not ready yet. Retrying in $RETRY_INTERVAL seconds..."
            sleep $RETRY_INTERVAL
          done

          echo "API did not start within the given time. Please review 'Debug API Container Logs' step output for errors."
          exit 1

      - name: Check Docker logs
        run: |
          docker logs a

      - name: Stop and Remove Docker Containers
        if: always()
        run: docker compose down