name: "Agripredict Docker Test"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
   docker-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Build, Start and Test Docker Compose
        run: |
          docker compose up -d --build

      - name: Check Docker logs
        run: |
          docker logs agripredict-api

      - name: Stop and Remove Docker Containers
        if: always()
        run: docker compose down